# Generated by Django 3.0.5 on 2020-04-12 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='projects',
        ),
    ]
